In [123]:
import pandas as pd

In [112]:
data = {'name':['alice','bob'],'age':[25,30]}
data

{'name': ['alice', 'bob'], 'age': [25, 30]}

In [113]:
df = pd.DataFrame(data)

In [52]:
df

    name gender
0  alice      F
1    bob      M

In [12]:
lst = [['alice',25],['bob',30]]

In [13]:
df = pd.DataFrame(lst,columns=['name','age'])

In [14]:
df

    name  age
0  alice   25
1    bob   30

In [17]:
df.head()

    name  age
0  alice   25
1    bob   30

In [19]:
df.tail()

    name  age
0  alice   25
1    bob   30

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      str
 1   age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [23]:
df.describe()

             age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [25]:
df['name']

0    alice
1      bob
Name: name, dtype: str

In [27]:
df[['name','age']]

    name  age
0  alice   25
1    bob   30

In [29]:
df.loc[0]

name    alice
age        25
Name: 0, dtype: object

In [31]:
df.iloc[1]

name    bob
age      30
Name: 1, dtype: object

In [33]:
df[df['age']>25]

  name  age
1  bob   30

In [67]:
df['gender'] = ['F','M']

In [37]:
df

    name  age gender
0  alice   25      F
1    bob   30      M

In [41]:
df.drop('age', axis=1 , inplace = True)

In [42]:
df

    name gender
0  alice      F
1    bob      M

In [44]:
df.isnull()

    name  gender
0  False   False
1  False   False

In [46]:
df.dropna()

    name gender
0  alice      F
1    bob      M

In [48]:
df.fillna(0)

    name gender
0  alice      F
1    bob      M

In [68]:
df.groupby('gender')['age'].mean()
df

    name  age gender
0  alice   25      F
1    bob   30      M

In [96]:
df1 = pd.DataFrame({'key':[1,2,],'name':['alice','bob']})
df2 = pd.DataFrame({'key':[1,2,],'age':[25,30]})

In [94]:
pd.merge(df1,df2,on='key')

   key   name  age
0    1  alice   25
1    2    bob   30

In [97]:
df1=df1.set_index('key')
df2=df2.set_index('key')

In [98]:
df1.join(df2)

      name  age
key
1    alice   25
2      bob   30

In [ ]:
df = pd.read_csv('data.csv')

In [114]:
df

    name  age
0  alice   25
1    bob   30

In [116]:
df.to_csv('output.csv',index = False)

In [118]:
df.sort_values('age')

    name  age
0  alice   25
1    bob   30

In [120]:
df['age'].apply(lambda x:x + 1)

0    26
1    31
Name: age, dtype: int64

In [122]:
df['name'].unique()

<StringArray>
['alice', 'bob']
Length: 2, dtype: str

In [124]:
df['age'].value_counts()

age
25    1
30    1
Name: count, dtype: int64